### ISSUE TITLE
Errors are badly formatted

### ISSUE THREAD

**Issue by freaz** [superfaceai/service-client#68]
Provide a general summary of the issue in the Title above

## Expected Behavior

I should see detailed information

## Current Behavior

```
Store responded with status: 400 on: /providers Validation failed: [object Object],[object Object],[object Object],[object Object],[object Object]
```

## Possible Solution

Not obligatory, but suggest a fix/reason for the bug

## Steps to Reproduce

Create provider with invalid definition

## Your Environment

using stating to publish capabiltiies to production

**Comment by janhalama** [comment]
According to https://datatracker.ietf.org/doc/html/rfc7807#section-3.1 `detail` should be string. The way sevice-client prints the error is correct.

Options:

1.Print schema validation errors in Brain and send `detail` as string instead of json
2.Define custom `application/problem+json` type

RFC7807 requires that type is in uri format, could be `https://superface.ai/app-problems/json-schema-validation-error`. We can then extend problem json document with custom property `validation-errors` and use it in `service-client` to print details about the error.

**Comment by freaz** [comment]
So the issue is on service side in exception filter which doesn't ensure that the detail is a string.

**Comment by janhalama** [comment]
Right, I will open PR with fix in Brain.
